### ISSUE TITLE
Wrong Euler axis sequence in from_euler() method

### ISSUE THREAD

**Issue by joaomoura24** [IRIM-Technology-Transition-Lab/quaternions#10]
In the following line of the method from_euler():

https://github.com/IRIM-Technology-Transition-Lab/quaternions/blob/6496d11d4b9fbe0d5ad630ae93914ee9092b5c46/quaternions/quaternion.py#L151

The sequence ['y', 'y', 'x'] is not an Euler sequence.
From my testing this should read: ['z', 'y', 'x'].

**Comment by mjsobrep** [comment]
Hey @joaomoura24 thanks for pointing that out!! I no longer push new code to this repository. I fixed it on the fork that I maintain (https://github.com/mjsobrep/quaternions/commit/216f0bdebc444829c82295860d5dfc26ef2554c6) and added a note to the readme here that this repository is no longer maintained.

**Comment by joaomoura24** [comment]
Hi @mjsobrep. That's great - I'll re-fork from your main repo then.
